name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_CONFIGURATION: 'Release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install NPM packages
      run: npm install

    - name: Install Gulp
      run: |
        npm install -g gulp-cli
        npm install -g gulp

    - name: Show Gulp Version
      run: gulp -v

    - name: Compile Sass assets
      run: ./node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot
          
    - name: Run Gulp tasks
      run: gulp

    - name: Write build info
      run: echo "${{ github.workflow }}, ${{ github.run_id }}, ${{ github.run_number }}" > buildinfo.txt
      working-directory: Tailspin.SpaceGame.Web/wwwroot

    - name: Restore project dependencies
      run: dotnet restore 'Tailspin.SpaceGame.Web.csproj'
      working-directory: Tailspin.SpaceGame.Web

    - name: Build and Publish the project - Release
      run: |
        cd Tailspin.SpaceGame.Web
        dotnet build --no-restore --configuration Release
        dotnet publish --no-build --configuration Release --output '../dotnet-tailspin-spacegame'
