name: Build and Publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_CONFIGURATION: 'Release'
      wwwRootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      DOTNET_VERSION: '6.x'
      nodeVersion: '14'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.nodeVersion }}

    - name: Install NPM packages
      run: npm install

    - name: Install Gulp
      run: |
        npm install -g gulp-cli
        npm install -g gulp

    - name: Show Gulp Version
      run: gulp -v

    - name: Compile Sass assets
      run: ./node_modules/.bin/node-sass ${{ env.wwwRootDir }} --output ${{ env.wwwRootDir }}
          
    - name: Run Gulp tasks
      run: gulp

    - name: Write build info
      run: echo "${{ github.workflow }}, ${{ github.run_id }}, ${{ github.run_number }}" > buildinfo.txt
      working-directory: ${{ env.wwwRootDir }}

    - name: Restore project dependencies
      run: dotnet restore 'Tailspin.SpaceGame.Web.csproj'
      working-directory: Tailspin.SpaceGame.Web

    - name: Build and Publish the project - Release
      run: |
        cd Tailspin.SpaceGame.Web
        dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}
        dotnet publish --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --output ../dotnet-tailspin-spacegame
